### ISSUE TITLE
gellery_get error

### ISSUE THREAD

**Issue by i-keng** [regosen/gallery_get#1]
Traceback (most recent call last):
  File "gallery_get.py", line 225, in run
    self.run_internal()
  File "gallery_get.py", line 197, in run_internal
    rpage = urllib.urlopen(info.redirect).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
error: [Errno 54] Connection reset by peer
Using params: ['http://xhamster.com/photos/gallery/1481007/thai_university_teen.html', '../Pics/', False]

**Comment by regosen** [comment]
Hi i-keng, will you try it again?  Looks like connection was reset.

I just tried using your parameters and didn't have any issues.

**Comment by i-keng** [comment]
Ok thanks

-- 
Jirattiti Phumhoradee
Sent with Airmail

On June 21, 2558 BE at 11:06:42 PM, Rego Sen (notifications@github.com) wrote:

Hi i-keng, will you try it again? Looks like connection was reset.

I just tried using your parameters and didn't have any issues.
