### ISSUE TITLE
Generic plugin grabs thumbnail images from gogoimage.org

### ISSUE THREAD

**Issue by rezso** [regosen/gallery_get#12]
Try this:
python ./gallery_get.py http://vipergirls.to/threads/1362658-Giselle-Teen-Bares-All-%28x60%29
The script will download the thumbnail images, because gogoimage.org uses 'small' instead of 'thumb'.
Ugly, but working fix:
links = filter(lambda x: not "small" in x.lower(), links) # exclude thumbnails, gogoimage.org
after the
links = filter(lambda x: not "thumb" in x.lower(), links) # exclude thumbnails
line.

**Comment by regosen** [comment]
I just added a plugin for gogoimage.org, try it now.
