### ISSUE TITLE
imagefap plugin doesn't works

### ISSUE THREAD

**Issue by rezso** [regosen/gallery_get#2]
I can't download anything from imagefap.
After changing the fap.to/images/full/ url to x.imagefapusercontent.com, the script downloaded 17 images of 139, and stopped.

**Comment by regosen** [comment]
Thanks for reporting this!  Looks like they changed their link format.

I just updated the plugin- grab latest code and try again?

**Comment by rezso** [comment]
This update is same, that I made.
Please try to download this gallery: http://www.imagefap.com/pictures/4547813/MvPrime-Flashing-29
The plugin downloads only 17 images.

**Comment by regosen** [comment]
Ah, now I see the problem.  Ok, now it should work for multiple-page galleries.

Let me know if it's fixed for you now.

**Comment by rezso** [comment]
Now the script downloaded 131 images of 139.
I get these messages during the download:

No links found at redirect page!  Check regex.  Redirect URL:
http://www.imagefap.com/photo/753834183/?pgid=&gid=4547813&page=3&idx=72
No links found at redirect page!  Check regex.  Redirect URL:
http://www.imagefap.com/photo/952783800/?pgid=&gid=4547813&page=2&idx=70
No links found at redirect page!  Check regex.  Redirect URL:
http://www.imagefap.com/photo/1817046719/?pgid=&gid=4547813&page=0&idx=8
No links found at redirect page!  Check regex.  Redirect URL:
http://www.imagefap.com/photo/1358174533/?pgid=&gid=4547813&page=2&idx=71
No links found at redirect page!  Check regex.  Redirect URL:
http://www.imagefap.com/photo/1652309746/?pgid=&gid=4547813&page=1&idx=30
No links found at redirect page!  Check regex.  Redirect URL:
No links found at redirect page!  Check regex.  Redirect URL:
http://www.imagefap.com/photo/1359450053/?pgid=&gid=4547813&page=0&idx=7
No links found at redirect page!  Check regex.  Redirect URL:
http://www.imagefap.com/photo/1014291059/?pgid=&gid=4547813&page=0&idx=6

http://www.imagefap.com/photo/1271161907/?pgid=&gid=4547813&page=0&idx=9

**Comment by regosen** [comment]
Shoot, some of the plugins didn't account for files ending in .jpeg instead of .jpg.

Thanks for catching this- I've updated the plugins to account for this, so you should be getting all 139 files now.

**Comment by rezso** [comment]
Yes, it works now fine.
Thank you.
