### ISSUE TITLE
Installation with pip fails on Windows 10

### ISSUE THREAD

**Issue by Hrxn** [regosen/gallery_get#27]
```
E:\>pip install gallery_get
Collecting gallery_get
  Using cached gallery_get-1.7.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hrxn\AppData\Local\Temp\pip-build-mfy318j8\gallery-get\setup.py", line 5, in <module>
        mods += map(lambda x: "gallery_plugins/%s" % x, filter(lambda x: x.endswith(".py"), os.listdir("gallery_plugins")))
    TypeError: unsupported operand type(s) for +=: 'filter' and 'map'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Hrxn\AppData\Local\Temp\pip-build-mfy318j8\gallery-get\

E:\>
```

Windows 10 x64
Python 3.6.0 x64

**Comment by regosen** [comment]
Thanks for reporting this.  I think I've fixed it now with version 1.7.9 (it was a compatibility issue with Python 3).

Will you try "pip install gallery_get" again?

**Comment by Hrxn** [comment]
```
D:\>pip3 install gallery_get
Collecting gallery_get
  Downloading gallery_get-1.7.9.tar.gz
Installing collected packages: gallery-get
  Running setup.py install for gallery-get ... done
Successfully installed gallery-get-1.7.9

D:\>
```

and PIP

```
D:\>pip list --format=legacy
arrow (0.10.0)
classifier (1.7)
gallery-dl (0.7.0)
gallery-get (1.7.9)
iso-639 (0.4.5)
iso3166 (0.8)
pip (9.0.1)
pycryptodome (3.4.5)
python-dateutil (2.6.0)
requests (2.13.0)
setuptools (28.8.0)
six (1.10.0)
streamlink (0.4.0)

D:\>
```

But, usage from the command line as in README.md
```
D:\>python gallery_get.py
python: can't open file 'gallery_get.py': [Errno 2] No such file or directory

D:\>
```

Strange..
Do I need to put gallery_get.py somewhere in my PATH manually? Although that shouldn't be the case, I think.

**Comment by regosen** [comment]
I've only used "pip install" to install modules.  For anything I would use at a command prompt, I download directly (either via github or the PyPI page).  I would recommend that you download to a folder where you normally run your scripts / point to with PATH.

That being said, is there a pip install option or setup.py configuration that covers this use case?  (I don't know about it, and I'm having trouble finding anything like that.)  If not, I'll update my README to note the more restricted use case for "pip install".

**Comment by Hrxn** [comment]
Yeah, using it the classical way (python file.py) works.

Or, in my case, via .cmd
`python D:\Src\gallery_get-master\gallery_get.py %*`

Not sure about the specific use case you're mentioning here, though.
