### ISSUE TITLE
XVideos Support (xVideos.com)

### ISSUE THREAD

**Issue by Pyth0nPrince** [regosen/gallery_get#33]
How difficult would it be to modify existing script/plugins (such as xHamster) to allow for downloading of xVideos image galleries/albums?

**Comment by regosen** [comment]
I just had a look, and it was pretty easy.  I just added a plugin now for xVideos.  Let me know if it works for you.

**Comment by regosen** [comment]
I just got confirmation from another user that the xVideos plugin works, closing this issue.
