### ISSUE TITLE
Plugin update

### ISSUE THREAD

**Issue by Superman627** [regosen/gallery_get#34]
i think its not working anymore i tried xhamster and its gives me this 
"plugin may need updating.
Sites occasionally change their markup.  Check if this tool has an update.
 - https://github.com/regosen/gallery_get
 - pip install gallery_get --update
Errors were encountered!  Please check messages above." so the plugins might need an update

**Comment by regosen** [comment]
Hi @Superman627 - I just updated the plugin to match their revamped site.  Grab the latest version of this repository and try again.  Let me know if it works!

**Comment by Superman627** [comment]
Yea it works! Thanks for the fix really appreciate it and oh by the way is
there a possible way you can add pornhub plugins or that isnt possible?

On Dec 7, 2017 12:23 PM, "Rego Sen" <notifications@github.com> wrote:

Hi @Superman627 <https://github.com/superman627> - I just updated the
plugin to match their revamped site. Grab the latest version of this
repository and try again. Let me know if it works!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/regosen/gallery_get/issues/34#issuecomment-350036677>,
or mute the thread

**Comment by Superman627** [comment]
Yea it works! Thanks for the fix and by the ways is it possible to add a PHub plugin or its not possible?

**Comment by regosen** [comment]
I had a look, and it was pretty easy to download a video from a PHub page.  I just added a plugin now.  Happy holidays.

**Comment by Superman627** [comment]
Thanks Man i appreciated the plugins you added but when i tried it for ph it keep saying "skipping incessible link" when i try video and when i try the galleries they failed to save

**Comment by regosen** [comment]
I got that too, but it worked and downloaded when I tried the second time.  I'll look into it this week.

**Comment by regosen** [comment]
Ok, I think I fixed it- the xVideos plugin was accidentally claiming other galleries.  I just updated the plugin, try it now.

**Comment by Superman627** [comment]
Nice! the xvideos plugin is working but the PH plugin not working. And does the two plugin cover only videos does it cover videos and galleries because i was wondering if both xvideos/PH plugins can get galleries as well

**Comment by regosen** [comment]
Ah, I didn't even realize PH had image galleries.  I just added a new plugin for their image galleries, try that now.

I don't see any image galleries on xVideos.com though, can you send me a link of an example?  (Feel free to send a private message if you don't want to share the link here)

And I can't reproduce the PH video plugin not working issue, are you using a URL with the following format?  https://www.pornhub.com/view_video.php?viewkey=blahblahblah    If you are using that format and it still doesn't work for you, please send me a link to the example you're using.

**Comment by Superman627** [comment]
It works just tried it both PH and Xvideos galleries are working Thanks! And for galleries on xvideos they should be on any account

**Comment by regosen** [comment]
That's great to hear!
