### ISSUE TITLE
ERROR getting json data after several retries!  Does the user exist? 

### ISSUE THREAD

**Issue by sdenaro** [regosen/gallery_get#36]
The user exists, but it is using the new style reddit /user/ profile page not the old one. The JSON should be the same so I am unsure what's breaking here.

> Requesting JSON data from reddit...
> ERROR getting json data after several retries!  Does the user exist?
> If so, try saving the contents of the following to <<username>>.json and try again.
> http://www.reddit.com/user/<<username>>/submitted/.json?limit=1000
> Done!

**Comment by regosen** [comment]
Hi, I just tried a few reddit usernames and can't reproduce this.  According to what you pasted, the script used "<>" as the user name.  How did you get the script to do that.  I assume you didn't simply enter <> as the username.

**Comment by sdenaro** [comment]
Can you try with this username:

 17reasons

Requesting JSON data from reddit...
ERROR getting json data after several retries!  Does the user exist?
If so, try saving the contents of the following to 17reasons.json and try again.
http://www.reddit.com/user/17reasons/submitted/.json?limit=1000

**Comment by regosen** [comment]
Thanks for the info!  Odd, I'm able to collect pictures from that user (cool scenery).  I tried with Python 3.6.1 as well as 2.7.10, both on OSX though.

Can you try this?  Paste the URL from the error message into your browser:

http://www.reddit.com/user/17reasons/submitted/.json?limit=1000

You should see a bunch of JSON-formatted text that starts out like this:
```
{"kind": "Listing", "data": {"after": null, "dist": 37, "modhash": "7mj8u47vwjd39f1d68572b992ce7729ece1656a441c8137fec", "whitelist_status": "promo_all", "children": [{"kind": "t3", "data": {"domain": "i.redd.it", ...
```
What do you see?

**Comment by sdenaro** [comment]
And it looks like gallery_get.py is working with my proxy set up but reddit_get.py isn't. I'm going to look into this more over the weekend.

**Comment by regosen** [comment]
Can you try one more thing for me?  In reddit_get.py change this:
```
        if not "data" in reddit_json:
            print("ERROR getting json data after several retries!  Does the user exist?")
```
to this (added an extra line):
```
        if not "data" in reddit_json:
            print(reddit_json)
            print("ERROR getting json data after several retries!  Does the user exist?")
```
and post the new output.

**Comment by sdenaro** [comment]
I get this:

`python3 ~/prog/gallery_get/reddit_get.py 17reasons
Requesting JSON data from reddit...
{}
ERROR getting json data after several retries!  Does the user exist?
If so, try saving the contents of the following to 17reasons.json and try again.
http://www.reddit.com/user/17reasons/submitted/.json?limit=1000
Done!`

**Comment by regosen** [comment]
Oh interesting, that's not what I expected.  I wonder if it's cached for you somehow.  Can you try it from a different computer?

**Comment by sdenaro** [comment]
So it's working on my local machine and it's failing on my pi when the tor proxy is on and working when the tor proxy is off. I'm 90% sure this is just not working with the socks5 proxy.

**Comment by sdenaro** [comment]
I replaced this

`USER_QUERY = "http://www.reddit.com/user/%s/submitted/.json?limit=1000"
`
with this

`USER_QUERY = "https://www.reddit.com/user/%s/submitted/.json?limit=1000"`

And it's now working. 

Looks like this is an issue with my proxy set up failing to rewrite to https from http.

You can close this issue, but it wouldn't hurt to switch to https by default.

**Comment by regosen** [comment]
Ah!  I've gone ahead and submitted an update to this repository.  Thanks for helping to improve this project!
