### ISSUE TITLE
ImageFap does not work with png images.

### ISSUE THREAD

**Issue by Notay** [regosen/gallery_get#5]
Don't know regex, but can make it work by changing:
`direct_links = r'name="mainPhoto".+?(http://x.imagefapusercontent.com/.+?\.jpe?g)'`
to
`direct_links = r'name="mainPhoto".+?(http://x.imagefapusercontent.com/.+?\.png)'`

**Comment by Hrxn** [comment]
Well, then `direct_links` would only get *.png

Maybe try this one instead:

`http://x.imagefapusercontent.com/.+?(\.jpe?g?|.png|.gif)`

So:

`direct_links = r'name="mainPhoto".+?(http://x.imagefapusercontent.com/.+?(\.jpe?g?|.png|.gif))'`

**Comment by regosen** [comment]
Should be fixed now with change from @Notay
