### ISSUE TITLE
Xvide plugin update

### ISSUE THREAD

**Issue by Superman627** [regosen/gallery_get#50]
Errors were encountered when using plugin and just said that plugin may need update due to sites markup changes

**Comment by regosen** [comment]
I'm not familiar with "Xvide" and gallery_get doesn't have a custom plugin for that.  When you enter the url does it say "Using generic plugin..." ?  (And if you can share the actual URL you used, even better)

**Comment by Superman627** [comment]
oh i meant to say the xvideos plugin lol and yes everything works fine and it detects and uses the appropriate plugin but it say that it the plugin might need a update

**Comment by Superman627** [comment]
One more thing is it possible to make a Vk.com plugin by itself instead of the the generic plugin because when testing the VK site it does detects as a generic plugin and when i try to get an example from 
an group timeline or group album it only gets some of the gallery and not all of it. Some galleries work some dont its like you get a few photo and some icons or what ever else is on the site and when it does work the photos come out thumbnail size and not the original size like here are some examples if you want to check it out.
https://vk.com/musclecars
https://vk.com/albums-27744747
https://vk.com/album-27744747_0
Thumbnail copy - https://pp.userapi.com/oxVpiBZ_hxX4b8vaPCh_pPqFmAW4ed6Xsna-Bw/X8wHd-TeSk4.jpg 
Original Copy - https://pp.userapi.com/VMEjWu8u3AEa9dttp4GAvWojqASHDFEuX_dmWQ/u9knbGDNU8M.jpg
https://vk.com/album-100636219_220170247
Im just using these as example and test purposes

**Comment by regosen** [comment]
Hi, I just tried an xvideos link and it works for me.  Can you post or email me with a URL that failed?

**Comment by regosen** [comment]
I just updated the repo with support for xVideos galleries as well.  Closing this issue.
