### ISSUE TITLE
Download from imagebam.com not works

### ISSUE THREAD

**Issue by rezso** [regosen/gallery_get#57]
gallery_get doesn' found any links on imagebam pages: "No links found at redirect page: http://www.imagebam.com/image/9bf929479773453"
The http://www.imagebam.com/image/9bf929479773453 is an "Continue to your image" page, but it contains the link to image in the meta headers:
`<meta property="og:image" content="http://images3.imagebam.com/08/ac/f4/9bf929479773453.jpg"/>`

**Comment by regosen** [comment]
I just added a plugin for imagebam.  Can you get the latest version of gallery_get and try again?

**Comment by rezso** [comment]
I tried, but not works (this page contains many images from imagebam.com): 

python gallery_get.py https://vipergirls.to/threads/1670038-\(\(\(-Hot-and-Sweet-and-Pretty-Amateur-Babes-Sets-lt-lt-lt-gt-gt-gt-2016-\)\)\)-NEW
Using generic plugin...
WARNING: Failed to open redirect https://vipergirls.to/threads/index.php?s=f743b0e897ad70654153186a2ca8ec8c
WARNING: Failed to open redirect https://vipergirls.to/threads/forum.php?s=f743b0e897ad70654153186a2ca8ec8c
No links found at redirect page: http://www.imagebam.com/image/9bf929479773453
No links found at redirect page: http://www.imagebam.com/image/3b8452479773438
[....]

If I rename the plugin_imagebam.py to plugin_generic.py:

python gallery_get.py https://vipergirls.to/threads/1670038-\(\(\(-Hot-and-Sweet-and-Pretty-Amateur-Babes-Sets-lt-lt-lt-gt-gt-gt-2016-\)\)\)-NEW
Using generic plugin...
No links found at https://vipergirls.to/threads/1670038-(((-Hot-and-Sweet-and-Pretty-Amateur-Babes-Sets-lt-lt-lt-gt-gt-gt-2016-)))-NEW, please check URL and try again.
Sites occasionally change their markup.  Check if this tool has an update.
 - https://github.com/regosen/gallery_get
 - pip install gallery_get --update
Errors were encountered!  Please check messages above.

**Comment by regosen** [comment]
I just checked in a fix to support generic galleries that link to plugin-supported sites.  I believe this will address your examples as well.  Can you update gallery_get and try again?

**Comment by rezso** [comment]
I tried the updated gallery_get.py. It works fine now, thank you.
