### ISSUE TITLE
Vipergirls.to

### ISSUE THREAD

**Issue by youngdarwin** [regosen/gallery_get#58]
I tried the script on a gallery at this site and the url was "inaccessible". Clicking a gallery sends you to imx.to which is also inaccessible:

$ ./gallery_get.py 
Input URL: https://imx.to/g/crok
Destination (/home/tmp5/caption/sets): 
Using generic plugin...
Skipping inaccessible link: https://imx.to/g/crok
Done!

I'm not very experienced with python. I guess this means the page didn't resolve or didn't decode. Is there a way to troubleshoot? Are these galleys compatible with this script?

**Comment by regosen** [comment]
I just checked in a fix to support generic galleries that link to plugin-supported sites. I believe this will address your examples as well. Can you update gallery_get and try again?

**Comment by youngdarwin** [comment]
Seems to work great. Thanks!
