### ISSUE TITLE
RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by GregBueno** [regosen/gallery_get#61]
![image](https://user-images.githubusercontent.com/48804211/60989459-780c6200-a31c-11e9-8c98-7fb0f76b6194.png)
Error -> RemoteDisconnected: Remote end closed connection without response

To solve this error in xhamster urls, I replace the User-Agent like:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36`

![image](https://user-images.githubusercontent.com/48804211/60989764-21535800-a31d-11e9-91c9-b2795b784e0d.png)

**Comment by regosen** [comment]
Thanks for the suggestion, I just made the change, and indeed that does seem to help!

Please try again with the new version of gallery_get.

**Comment by GregBueno** [comment]
It's working now!
