### ISSUE TITLE
XHamster index crawl broke

### ISSUE THREAD

**Issue by youngdarwin** [regosen/gallery_get#66]
xHamster changed the syntax (Merry Christmas!) surrounding next index pages, so the script cannot process them. As a result, only one page (of about 61 images) is downloaded. While you can run the script on each page, that's a hassle. To fix this, line 21 of the gallery_plugins/plugin_xHamster.py needs to change from:
`        next_url = re.findall(r'rel="next" href="(\S+?)"', indexed_source)`

to:
`        next_url = re.findall(r'data-page="next" href="(\S+?)"', indexed_source)`

**Comment by regosen** [comment]
Thanks for determining the fix!  I verified it on my end and pushed the changes.
