### ISSUE TITLE
xHamster title change breaks gg

### ISSUE THREAD

**Issue by youngdarwin** [regosen/gallery_get#70]
gg started downloading "Untitled Gallery" from xHamster. Just need to tweak line 14:

```
14c14
< title = r'<title>(.*?) - xHamster.com</title>'
---
> title = r'<title>(.*) | xHamster</title>'
```
Don't think '?' is needed and it was matching only the first word, so I removed it. Maybe the pipe needs to be escaped?

**Comment by regosen** [comment]
Thanks for the suggestion!  That worked for me as well.

Release 1.8.13 has the fix.
