### ISSUE TITLE
Enhancement: Skipping existing file is too slow

### ISSUE THREAD

**Issue by youngdarwin** [regosen/gallery_get#74]
I don't often re-DL a URL, but testing fixes for issue #73 I ran GG repeatedly on the same URL where it would crash on item 130. It took about 2 minutes for each test because I'm pretty sure GG is sleeping each time it processes a file, regardless of whether the file is being downloaded or skipped. 

I'm all for having a small delay to prevent hammering the server, but when GG skips a file, it just compares the string it's parsed from crawling index pages to files on disk **and doesn't touch the server, right?** 

Is that true? I don't trust my knowledge of Python to verify this...

But if skipping a file has no effect on the server, then I'd really, really like it to also skip sleeping (and not pause after each skipped file). Is that possible? Am I understanding correctly?

**Comment by regosen** [comment]
While there are sleep commands in GG, it doesn't correspond to each destination file.  Depending on the gallery you used, if each file's url comes from a redirect link, then the script has to request each redirect URL before getting the final image URL and determining if the image is skippable.  

Those redirect URLs take time and add up, regardless of whether the final image URLs can be skipped.  But maybe that's not what's happening in your case?  Feel free to provide example links that cause this issue, either here or privately through my profile contact info.
