### ISSUE TITLE
xhamster new website adress at localxh.com

### ISSUE THREAD

**Issue by ntagmr** [regosen/gallery_get#85]
Cant download gallery from xhamster, is it because its web address now localxh.com?

**Comment by regosen** [comment]
Looks like existing galleries still work correctly using the old domain, can you provide a URL with the new domain?

**Comment by Nikolai-RMR** [comment]
localhx.com appears to be a third-party clone of xHamster that simply attempts to throw pop-up ads in your face, from the preliminary information that I've gathered. I don't have reason to believe that localxh.com is associated with xHamster. I do believe however that this issue should be closed.

**Comment by regosen** [comment]
Thanks for the research, closing issue
